version: '3'

services:
  mosquitto:
    container_name: mqtt_broker
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - "1883:1883"
    restart: always
 
  python:
    container_name: mqtt_python
    build:
      context: .
      dockerfile: ./Dockerfile-python
    volumes:
      - ./python:/code
    restart: unless-stopped
