version: '3'

services:
  mosquitto:
    container_name: mqtt_broker
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
 
  python:
    container_name: mqtt_python
    build:
      context: .
      dockerfile: ./Dockerfile-python
    volumes:
      - ./code:/code
    restart: always

  api:
    container_name: mqtt_api
    build:
      context: .
      dockerfile: ./Dockerfile-fastapi
    volumes:
      - ./api:/api/app
    ports:
      - "8000:80"
    restart: always
